language: node_js
sudo: false
node_js:
  - "4.4"
  - "5.1"
# Send coverage data to Coveralls
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
